apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: nodeapp
        image: oskartinez/node-docker:v2
        volumeMounts:
        - mountPath: /logs
          name: my-pvc-volume
        ports:
        - containerPort: 8080
      volumes:
      - name: my-pvc-volume
        persistentVolumeClaim:
          claimName: mi-pvc
